version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    reviewers:
      - "g-andrade"
    schedule:
      # Consider increasing frequency if Sqids ever gets dependencies that are
      # not dev-only.
      interval: "monthly"
